Copyright **`(c)`** 2025 Giovanni Squillero `<giovanni.squillero@polito.it>`  
[`https://github.com/squillero/computational-intelligence`](https://github.com/squillero/computational-intelligence)  
Free under certain conditions — see the [`license`](https://github.com/squillero/computational-intelligence/blob/master/LICENSE.md) for details.  

In [3]:
import numpy as np

In [85]:
NUM_KNAPSACKS = 2
NUM_ITEMS = 10
NUM_DIMENSIONS = 2

In [5]:
NUM_KNAPSACKS = 2
NUM_ITEMS = 3
NUM_DIMENSIONS = 2

three random generated data structures
values -> vector of the values
weight -> vector(1 dimension)/matrix(multiple dimensions) conteining the weights of each element
constraint -> vector (or value if the problem is 1 dimension) containing the limit of each dimension

In [86]:
VALUES = np.random.randint(0, 100, size=NUM_ITEMS)
WEIGHTS = np.random.randint(0, 100, size=(NUM_ITEMS, NUM_DIMENSIONS))
CONSTRAINTS = np.random.randint(0, 100 * NUM_ITEMS // NUM_KNAPSACKS, size=(NUM_KNAPSACKS, NUM_DIMENSIONS))

In [7]:
WEIGHTS

array([[68, 44],
       [54,  5],
       [48, 79]], dtype=int32)

In [8]:
CONSTRAINTS

array([[ 21, 105],
       [  6,  85]], dtype=int32)

Create initial solution: for each knapsack it's chosen a random solution in order to have a legal knapsack.
Iterate it for each knapsack. A mask must be added to avoid having the same object in all, which will be updated each time by making the OR operation of all the i-th element of each solution array

In [26]:
# A random solution
solution = np.array(
    [np.random.random(NUM_ITEMS) <0.5 for _ in range(NUM_KNAPSACKS)], dtype=np.bool
)

In [27]:
solution

array([[ True,  True,  True],
       [ True, False,  True]])

In [100]:
def checkKnapsack(solution, knapsack):
    #checks if the solution is valid
    return np.all(WEIGHTS[solution[knapsack]].sum(axis=0) <= CONSTRAINTS[knapsack])

def fillKnapsack(knapsacks, numKnapsack, mask):
    #process: get all the values that can be chosen, get a random set of items to put in the knapsack
    #         and then check if the solution is valid

    #variables needed to reset the problem in case it's stuck
    trials = 0
    max_trials = 50
    while True:

        #trials handler

        trials += 1
        if trials >= max_trials:
            return np.zeros_like(mask, dtype=bool)
        
        #choosing knapsack items

        chosen_items = np.random.choice(np.where(~mask)[0], size=np.random.randint(1, np.sum(~mask)+1), replace=False)
        new_mask = np.zeros_like(mask, dtype=bool)
        new_mask[chosen_items] = np.True_
        knapsackCopy = knapsacks.copy()
        knapsackCopy[numKnapsack] |= new_mask

        #checking if the knapsack is valid

        print(f"Trying items {chosen_items} for knapsack {numKnapsack}")
        if checkKnapsack(knapsackCopy, numKnapsack):
            return new_mask

def createSolution():
    #process: create a random solution for the knapsack problem

    while True:  # Outer loop to restart the for loop
        solution = np.zeros((NUM_KNAPSACKS, NUM_ITEMS), dtype=bool)
        mask = np.zeros(NUM_ITEMS, dtype=bool)
        for k in range(NUM_KNAPSACKS):
            solution[k] = fillKnapsack(solution, k, mask)
            if solution[k].sum() != 0:  # Condition to restart the loop
                mask |= solution[k]
                if(k == NUM_KNAPSACKS - 1):
                    return solution
                continue
            break  # Exit the for loop to restart

In [ ]:
solution = createSolution()
#initial solution with all knapsacks filled with a valid configuration
solution 

In [94]:
# Check that the same object does not appear in multiple knapsacks
np.all(solution.sum(axis=0) <= 1)

np.True_

In [ ]:
# Check if the solution is valid
all_knapsacks = np.any(solution, axis=0)
print("All knapsacks combined mask:", solution)
print("all_knapsacks:", all_knapsacks)
np.all(WEIGHTS[all_knapsacks].sum(axis=0) < CONSTRAINTS)

All knapsacks combined mask: [[False False  True False False  True False False  True False]
 [False  True False False  True False False False False False]]
all_knapsacks: [False  True  True False  True  True False False  True False]


np.False_

## TEST PROBLEMS

In [97]:
# Problem 1:
rng = np.random.default_rng(seed=42)
NUM_KNAPSACKS = 3
NUM_ITEMS = 20
NUM_DIMENSIONS = 2
VALUES = rng.integers(0, 100, size=NUM_ITEMS)
WEIGHTS = rng.integers(0, 100, size=(NUM_ITEMS, NUM_DIMENSIONS))
CONSTRAINTS = rng.integers(0, 100 * NUM_ITEMS // NUM_KNAPSACKS, size=NUM_DIMENSIONS)

In [101]:
# Problem 2:
rng = np.random.default_rng(seed=42)
NUM_KNAPSACKS = 10
NUM_ITEMS = 100
NUM_DIMENSIONS = 10
VALUES = rng.integers(0, 1000, size=NUM_ITEMS)
WEIGHTS = rng.integers(0, 1000, size=(NUM_ITEMS, NUM_DIMENSIONS))
CONSTRAINTS = rng.integers(1000 * 2, 1000 * NUM_ITEMS // NUM_KNAPSACKS, size=NUM_DIMENSIONS)

In [95]:
# Problem 3:
rng = np.random.default_rng(seed=42)
NUM_KNAPSACKS = 100
NUM_ITEMS = 5000
NUM_DIMENSIONS = 100
VALUES = rng.integers(0, 1000, size=NUM_ITEMS)
WEIGHTS = rng.integers(0, 1000, size=(NUM_ITEMS, NUM_DIMENSIONS))
CONSTRAINTS = rng.integers(1000 * 10, 1000 * 2 * NUM_ITEMS // NUM_KNAPSACKS, size=NUM_DIMENSIONS)